// <auto-generated />
using System;
using Hubtel.Wallets.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hubtel.Wallets.Persistence.Migrations
{
    [DbContext(typeof(HubtelWalletsDbContext))]
    partial class HubtelWalletsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hubtel.Wallets.Domain.Models.TblAsAccountScheme", b =>
                {
                    b.Property<int>("AsIdpk")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("asIDpk")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AsSchemeName")
                        .IsRequired()
                        .HasColumnName("asSchemeName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("AsTypeIdfk")
                        .HasColumnName("asTypeIDfk")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EditedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AsIdpk");

                    b.ToTable("tblAsAccountScheme");

                    b.HasData(
                        new
                        {
                            AsIdpk = 1,
                            AsSchemeName = "Mastercard",
                            AsTypeIdfk = 2,
                            CreationDate = new DateTime(2023, 5, 19, 15, 7, 56, 720, DateTimeKind.Utc).AddTicks(3825)
                        },
                        new
                        {
                            AsIdpk = 2,
                            AsSchemeName = "Visa",
                            AsTypeIdfk = 2,
                            CreationDate = new DateTime(2023, 5, 19, 15, 7, 56, 720, DateTimeKind.Utc).AddTicks(4731)
                        },
                        new
                        {
                            AsIdpk = 3,
                            AsSchemeName = "MTN",
                            AsTypeIdfk = 1,
                            CreationDate = new DateTime(2023, 5, 19, 15, 7, 56, 720, DateTimeKind.Utc).AddTicks(4756)
                        },
                        new
                        {
                            AsIdpk = 4,
                            AsSchemeName = "Vodafone",
                            AsTypeIdfk = 1,
                            CreationDate = new DateTime(2023, 5, 19, 15, 7, 56, 720, DateTimeKind.Utc).AddTicks(4758)
                        },
                        new
                        {
                            AsIdpk = 5,
                            AsSchemeName = "AirtelTigo",
                            AsTypeIdfk = 1,
                            CreationDate = new DateTime(2023, 5, 19, 15, 7, 56, 720, DateTimeKind.Utc).AddTicks(4760)
                        });
                });

            modelBuilder.Entity("Hubtel.Wallets.Domain.Models.TblTtype", b =>
                {
                    b.Property<int>("TIdpk")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tIDpk")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EditedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TTypeName")
                        .IsRequired()
                        .HasColumnName("tTypeName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("TIdpk");

                    b.ToTable("tblTType");

                    b.HasData(
                        new
                        {
                            TIdpk = 1,
                            CreationDate = new DateTime(2023, 5, 19, 15, 7, 56, 717, DateTimeKind.Local).AddTicks(1584),
                            TTypeName = "Momo"
                        },
                        new
                        {
                            TIdpk = 2,
                            CreationDate = new DateTime(2023, 5, 19, 15, 7, 56, 718, DateTimeKind.Local).AddTicks(1707),
                            TTypeName = "Card"
                        });
                });

            modelBuilder.Entity("Hubtel.Wallets.Domain.Models.TblUcaUserCreditAccount", b =>
                {
                    b.Property<int>("UcaIdpk")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ucaIDpk")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UcaAccountNumber")
                        .IsRequired()
                        .HasColumnName("ucaAccountNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UcaCreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ucaCreationDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UcaEditedDate")
                        .HasColumnName("ucaEditedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UcaSchemeIdfk")
                        .HasColumnName("ucaSchemeIDfk")
                        .HasColumnType("int");

                    b.Property<int>("UcaTypeIdfk")
                        .HasColumnName("ucaTypeIDfk")
                        .HasColumnType("int");

                    b.Property<string>("UcaUserIdfk")
                        .IsRequired()
                        .HasColumnName("ucaUserIDfk")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UcaIdpk");

                    b.ToTable("tblUcaUserCreditAccounts");

                    b.HasData(
                        new
                        {
                            UcaIdpk = 1,
                            UcaAccountNumber = "0552235521",
                            UcaCreationDate = new DateTime(2023, 5, 19, 15, 7, 56, 721, DateTimeKind.Utc).AddTicks(9846),
                            UcaSchemeIdfk = 3,
                            UcaTypeIdfk = 1,
                            UcaUserIdfk = "0be64bd1-d201-7821-9000-18937492a66d"
                        },
                        new
                        {
                            UcaIdpk = 2,
                            UcaAccountNumber = "0552474843",
                            UcaCreationDate = new DateTime(2023, 5, 19, 15, 7, 56, 722, DateTimeKind.Utc).AddTicks(1816),
                            UcaSchemeIdfk = 4,
                            UcaTypeIdfk = 1,
                            UcaUserIdfk = "0be64bd1-d201-7821-9000-18937492a66d"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
